### ISSUE TITLE
#marketing missing CTA: star on github

### ISSUE THREAD

**Issue by coderofsalvation** [yyx990803/buble#1]
This project is awesome, finally a KISS version of babel which doesn't choke my CPU.

I'm afraid the website ranks pretty good in google, but it's missing something essential: a star-button in the header or footer. (goto: https://buttons.github.io )

This is really essential to onboard new users imho, and rank higher in the github search.
(Kind of a 'watch later'-button like in youtube)

hope this helps!

**Comment by yyx990803** [comment]
Thanks but this is a fork :)

**Comment by coderofsalvation** [comment]
hehe ok thx for pointing that out :+1: 

You probably didn't hit the fork button, but created a new repo here (hence the reference is missing). I'll move this to the original :)
