### ISSUE TITLE
Sync with latest from Rich-Harris/buble (now on github)

### ISSUE THREAD

**Issue by jskrzypek** [yyx990803/buble#3]
Is it worth syncing the latest changes from https://github.com/Rich-Harris/buble/?

There are only minor merge conflicts

**Comment by jskrzypek** [comment]
See here for the merged branch on my fork: https://github.com/jskrzypek/buble/tree/merge/Rich-Harris

**Comment by yyx990803** [comment]
Feel free to submit a PR!

**Comment by yyx990803** [comment]
Synced with 0.19.3 which covers most of the updates in the past year.
